### ISSUE TITLE
Need some improvements!

### ISSUE THREAD

**Issue by maaudrana** [lorien/daysandbox_bot#25] opened 2018-07-15 14:21 UTC
No user can send link but except  if    it is  only from  www.example.com/...
Admin can send any link.
I wish you will add these features very soon.
Thank you

**Comment by lorien** [comment] 2019-01-29 17:04
> No user can send link but except if it is only from www.example.com/...

Duplicate of #29 Talking about white-list of domains makes sense only in context of idea that daysandbox blocks links (or most of links) from uses only in some time period (like 24 hours since joining chat). If you want to remove all links (except whitelisted domains) forever then it is not task for daysandbox. You can try https://t.me/watchdog_robot. But it does not have whitelist feature yet.

> Admin can send any link.

That is done.

Please write all futher questions and thoughts to group https://t.me/tgdev_en

**Closed by lorien** 2019-01-29 17:04 UTC
